# Generated by Django 2.1 on 2019-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('check_in_time', models.DateTimeField()),
                ('check_in_type', models.CharField(max_length=128)),
                ('overtime_hours', models.FloatField()),
                ('leave_days', models.FloatField()),
            ],
        ),
    ]
