# Generated by Django 2.1 on 2019-03-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cellphone',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='office_number',
            field=models.BigIntegerField(default='0'),
        ),
    ]
