# Generated by Django 2.1 on 2019-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190306_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='personal_id',
            field=models.BigIntegerField(default='0'),
        ),
    ]
