# Generated by Django 2.1 on 2019-03-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_value', models.CharField(choices=[('标题', 'first'), ('内容', 'second'), ('作者', 'third')], max_length=10)),
            ],
        ),
    ]
